sudo: required
language: node_js
node_js:
  - '8'
jobs:
  include:
    - stage: test
      name: 'Linting'
      script: npm run lint
    - stage: test
      name: 'Unit tests'
      script: npm run test
    - stage: test
      services:
        - docker
      before_install:
        - cd examples/react && npm install
      name: 'Visual tests: React DOM'
      script: npm run test-ci
    - stage: deploy
      script: skip
      if: (repo = "oblador/loki") AND (tag =~ ^test[0-9]+\\.[0-9]+\\.[0-9]+.*$)
      name: 'NPM'
      deploy:
        - provider: npm
          email: joel@oblador.se
